---
title: U.S.-Liberia trade
output: rmarkdown::github_document
---

Source: [U.S. Census Bureau](https://www.census.gov/foreign-trade/balance/c7650.html)

```{r data-prep, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, eval=TRUE, include=FALSE}

library(htmltab)
library(tidyverse)
library(lubridate)
library(knitr)
library(readxl)
library(httr)
library(formattable)

setwd("~/OneDrive/Code/Census-trade/")

url <- "https://www.census.gov/foreign-trade/balance/country.xlsx"
GET(url, write_disk(TF <- tempfile(fileext = ".xlsx")))
countries <- read_excel(TF)
countries <- as_tibble(countries)
attach(countries)

countries_long <- countries %>%
  pivot_longer(!year:CTYNAME,
               names_to = c("TYPE", "MONTH"),
               names_pattern = "^(\\D)(\\D\\D\\D)",
               values_to = "AMOUNT"
               ) %>%
  rename(YEAR = year)

imports <- filter(countries_long, TYPE == "I" & CTYNAME == "Liberia")
imports_by_year <- imports %>% group_by(YEAR) %>% summarise(TOTAL = sum(AMOUNT))

exports <- filter(countries_long, TYPE == "E" & CTYNAME == "Liberia")
exports_by_year <- exports %>% group_by(YEAR) %>% summarise(TOTAL = sum(AMOUNT))

merged <- merge(imports_by_year, exports_by_year, by = "YEAR")
names(merged) <- c("YEAR", "IMPORTS", "EXPORTS")

merged$BALANCE <- merged$EXPORTS - merged$IMPORTS
merged$YEAR <- parse_date_time(merged$YEAR, "Y")
merged_tbl <- merged

write.csv(merged_tbl, "merged_tbl.csv")

```

## U.S. trade balance with Liberia by year ####

```{r trade-balance, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, eval=TRUE}

merged_tbl$YEAR <- format(as.Date(merged$YEAR, format = "%Y-%m-%d"), "%Y")
ggplot(merged, aes(x = YEAR, y = BALANCE)) +
    geom_bar(stat = "identity") +
    labs(x = "Year", y = "Trade balance in U.S. dollars (millions)") +
    theme_minimal()

```

```{r imports-exports, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, eval=TRUE}

kable(merged_tbl, digits = 1)

```

## Imports from Liberia (in millions) ####

```{r imports-plot, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, eval=TRUE}

ggplot(merged, aes(x = YEAR, y = IMPORTS)) +
  geom_line() +
  labs(x = "Year", y = "Imports in U.S. dollars (millions)") +
  theme_minimal()

```

## Exports to Liberia (in millions) ####

```{r exports-plot, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, eval=TRUE}

ggplot(merged, aes(x = YEAR, y = EXPORTS)) +
  geom_line() +
  labs(x = "Year", y = "Exports in U.S. dollars (millions)") +
  theme_minimal()

```

## Top 30 exports from the U.S. to Liberia, 2021 (U.S. dollars) ####

```{r enduse-exports, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, eval=TRUE, include=FALSE}

url <- "https://www.census.gov/foreign-trade/statistics/product/enduse/exports/enduse_exports.xlsx"
GET(url, write_disk(TF <- tempfile(fileext = ".xlsx")))
end_exports <- read_excel(TF)
end_exports <- as_tibble(end_exports)
attach(end_exports)

end_ex_long <- end_exports %>%
  pivot_longer(!CTY_CODE:COMM_DESC,
               names_to = "YEAR",
               names_pattern = "value_(\\d\\d)",
               values_to = "TOTAL"
               )
write.csv(end_ex_long, "end_ex_long.csv")

```

```{r enduse-exports-table, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, eval=TRUE}

end_ex_long$YEAR <- sub("^", "20", end_ex_long$YEAR)
end_ex_long$YEAR <- parse_date_time(end_ex_long$YEAR, "Y")

ex_detail <- filter(end_ex_long, CTY_DESC == "Liberia")


# US exports to Liberia most recent year sorted from most to least
end_ex_latest_year <- ex_detail %>%
                  filter(year(YEAR) == max(year(YEAR))) %>%
                  group_by(COMM_DESC) %>%
                  summarise(TOTAL = sum(TOTAL)) %>%
                  arrange(desc(TOTAL))

kable(head(end_ex_latest_year, n = 30), digits = 1, format.args = list(big.mark = ","))

# # US exports to Liberia all years sorted from most to least ####
# end_ex_by_year <- ex_detail %>%
#                   group_by(COMM_DESC) %>%
#                   summarise(TOTAL = sum(TOTAL)) %>%
#                   arrange(desc(TOTAL))
# 
# top_20_ex <- head(end_ex_by_year, 20)
# top_20_ex$TOTAL <-  currency(top_20_ex$TOTAL, digits = 0L)
# top_20_ex <- rename(top_20_ex, EXPORT = COMM_DESC)
# kable(top_20_ex)

# Facet line plot of all US exports to Liberia by year ####
# end_comm_by_year <- ex_detail %>%
# group_by(YEAR) %>%
# arrange(desc(COMM_DESC))
# 
# end_comm_by_year <- select(end_comm_by_year, COMM_DESC, YEAR, TOTAL)
# 
# ggplot(end_comm_by_year, aes(x = YEAR, y = TOTAL, group = 1)) +
#   geom_line() +
#   facet_wrap(~COMM_DESC) +
#   ggtitle("US exports to Liberia")

```

## Top 30 imports from Liberia to the U.S. 2021 (U.S. dollars) ####

```{r enduse-imports, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, eval=TRUE, include=FALSE}

url <- "https://www.census.gov/foreign-trade/statistics/product/enduse/imports/enduse_imports.xlsx"
GET(url, write_disk(TF <- tempfile(fileext = ".xlsx")))
end_imports <- read_excel(TF)
end_imports <- as_tibble(end_imports)
attach(end_imports)

end_im_long <- end_imports %>%
  pivot_longer(!CTY_CODE:COMM_DESC,
               names_to = "YEAR",
               names_pattern = "value_(\\d\\d)",
               values_to = "TOTAL"
               )
write.csv(end_im_long, "end_im_long.csv")

end_im_long$YEAR <- sub("^", "20", end_im_long$YEAR)
end_im_long$YEAR <- parse_date_time(end_im_long$YEAR, "Y")

```

```{r enduse-imports-table, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, eval=TRUE}

im_detail <- filter(end_im_long, CTY_DESC == "Liberia")

end_im_by_year <- im_detail %>%
                  group_by(COMM_DESC) %>%
                  summarise(TOTAL =
                  sum(TOTAL)) %>%
                  arrange(desc(TOTAL))

top_20_im <- head(end_im_by_year, 20)
top_20_im$TOTAL <-  currency(top_20_im$TOTAL, digits = 0L)
top_20_im <- rename(top_20_im, IMPORT = COMM_DESC)
kable(top_20_im)

```

## Liberian rubber exports to U.S. ####

```{r rubber-plot, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, eval=TRUE}

rubber <- im_detail %>%
        filter(COMM_DESC == "Natural rubber")
ggplot(rubber, aes(x = YEAR, y = TOTAL)) +
        geom_line () +
        labs(x = "Year", y = "Exports to U.S. (in U.S. dollars)") +
        scale_y_continuous(labels = scales::dollar) +
        theme_minimal()
```

```{r rubber-table, echo=FALSE, error=FALSE, message=FALSE, warning=FALSE, eval=TRUE}

rubber_tbl <- rubber
rubber_tbl$YEAR <- format(as.Date(rubber_tbl$YEAR, format = "%Y-%m-%d"), "%Y")
rubber_tbl$TOTAL <-  currency(rubber_tbl$TOTAL, digits = 0L)
kable(select(rubber_tbl, YEAR, TOTAL), format.args = list(big.mark = ","))
```

